core/types/vote.go
core/vote/vote_manager.go
core/vote/vote_pool.go
core/vote/vote_pool_test.go
core/vote/vote_signer.go

Resolved vote related comments of fast finality review

---

core/blockchain_notries_test.go

close verifyTask when there is no valid peer and add UT tests
* ...

close verifyTask when there is no valid peer and add UT tests

---

consensus/consensus.go
consensus/parlia/parlia.go
core/blockchain.go
core/headerchain.go
core/types/vote.go
internal/ethapi/api.go
light/lightchain.go

fix justify and finalize logic

---

core/vote/vote_manager.go

In previous logic, while failedEvent sent by downloader, miner will still start, so it's required for voteManager to match this logic, set startVote as true if failedEvent received.

Fix startVote logic in voteManager

---

core/state/statedb.go

It is a typo, a small bug fix on `PutSyncPool()`
none
none
For detail pls refer the commit code.

Fix: a bug of Parallel 2.0 reused object pool

---

common/math/integer.go
consensus/parlia/parlia.go
go.sum

There should be enough online validators to vote for the fast finality, we think one block should gather 2/3*v+1 votes to get justified before, so the online validators should be at least 2/3*v+1.
However, once a block gathered 2/3*v votes, we can regard this block as justified, so we change the liveness from 2/3*v+1 to 2/3*v.
We assume there are less than 1/3*v validators who are malicious in the network, once a block gathered 2/3*v+ votes, we can regard this block as justified, and we can prove there will be no two blocks at the same height get justified under this assumption and constraints.
Assume the validators number is v, malicious validators are less than 1/3*v, the number is 1/3*v-1, if two blocks in the same height have received 2/3*v votes, then the total votes should be 4/3*v, …

change boneh fork liveness

---

core/vm/contracts.go
core/vm/contracts_test.go
core/vm/evm.go
params/protocol_params.go

This pr it to update the bls signature verification precompile contract.
The old precompile contract is only for fast finality's vote signature verification. In order to make it more general, we update the function.
* update bls verification precompile contract

feat: update bls verification precompile contract

---

core/vm/contracts.go
params/protocol_params.go

1. gas cost for blsSignatureVerify should be related with number of pubkeys
2. it should not run out of gas when failed to verify bls signature, so return ErrExecutionReverted instead

more rational gas and avoid running out of gas for blsSignatureVerify

---

core/vote/vote_manager.go
core/vote/vote_pool.go

1. we know that, 
if x and b are integer
_x -1 < b_       equal to         _x<=b_,  the latter one is more directly
_x+1>a_         equal to         _x>=a_,  the latter one is more directly
and the formers may lead to error easily, for example:
// Make sure in the range currentHeight-256~currentHeight+11.
if targetNumber+lowerLimitOfVoteBlockNumber-1 < headNumber || targetNumber > headNumber+upperLimitOfVoteBlockNumber {
log.Debug("BlockNumber of vote is outside the range of header-256~header+11, will be discarded")
return false
}
codes is not matched with annotations and log,
and the code express 'currentHeight-255~currentHeight+11  indeed
2. currentBlockNum+upperLimitOfVoteBlockNumber in included according to codes,
**for simplicity**, both boundary will be set to be included, votes in …

improved boundary handling and related annotations in core/vote

---

core/types/state_epoch.go
core/types/state_epoch_test.go
params/config.go

There are two hard forks, the first hard fork support new tx, epoch0, epoch1, second hard fork support epoch rotate. we could delay state expiry, fix issues, and upgrade features between two hard forks.
`STATE_EXPIRY_HARDFORK1_BLOCKNUM` indicates start epoch1, `STATE_EXPIRY_HARDFORK2_BLOCKNUM` indicates start epoch2 and start epoch rotate by EpochPeriod.
Epoch definition, calculate block epoch by:
```go
func getCurrentEpoch(block uint64) uint64 {
if block < STATE_EXPIRY_HARDFORK1_BLOCKNUM {
return 0
} else if block < STATE_EXPIRY_HARDFORK2_BLOCKNUM {
return 1
} else {
return (block - STATE_EXPIRY_HARDFORK2_BLOCKNUM) / EpochPeriod + 2
}
}
```
EpochPeriod = 7,008,000.
When merge furture Verkle Tree, from N epoch for special upgrade.
* hard fork: add state expiry hard …

state expiry: add state expiry hard forks and epoch compute.

---

consensus/parlia/parlia.go
consensus/parlia/snapshot.go
core/vote/vote_signer.go

no logic bugs, just some improvements
1. redundant codes
a. chain.GetHeaderByHash...
b. common.BytesToAddress...
2. useless var or func
isRecent..., just use recentVals as a set, ignore value of it
3. bug for log
log.Error only accept odd number params
* ...

improve some codes in core/vote and consensus

---

consensus/parlia/parlia.go
consensus/parlia/snapshot.go

change live nodes demand to 11 from 14
liveness of block proposal layer can be independent with liveness of block finalization layer
* ...

imporve liveness of block proposal layer

---

consensus/consensus.go
consensus/parlia/parlia.go
consensus/parlia/parlia_test.go
core/blockchain.go
core/forkchoice.go
core/headerchain.go
core/vote/vote_manager.go
core/vote/vote_pool.go
core/vote/vote_pool_test.go
ethclient/ethclient.go
internal/ethapi/api.go
light/lightchain.go

modify fork choice to improve security, details as following:
1. reimplement reorgNeededWithFastFinality by selecting higher justified block firstly,
and move it into forkchoice.go to avoid implement it twice
2. remove all naturally justified info, and fetch justified block number and hash 
from snapshot of consensus by using new func GetJustifiedNumberAndHash
3. change func signature of GetFinalizedHeader by removing input param `backward`,
use types.NaturallyFinalizedDist internally
4. repair test cases in parlia_test.go
a. finalized block and justified block are always same, it's wrong, now fixed
b. use new reorg logic
5. export GetJustifiedNumberAndHash as api instead of GetJustifiedHeader …

modify fork choice to prefer higher justified block number

---

eth/handler.go

fix BroadcastVote when GetTd, may lead to panic
Raw code:
deltaTD := new(big.Int).Abs(new(big.Int).Sub(h.chain.GetTd(h.chain.CurrentHeader().Hash(), h.chain.CurrentBlock().NumberU64()), peerTD))
Issue:
h.chain.CurrentHeader().Hash() and h.chain.CurrentBlock().NumberU64() may pointer to different block
so the first param of Sub may be nil
* ...

fix BroadcastVote when GetTd, may lead to panic

---

eth/handler.go
eth/peer.go
eth/protocols/bsc/handler.go
eth/protocols/bsc/handshake.go
eth/protocols/bsc/peer.go
eth/sync.go

no logic change, just some small improvements
1.  add some missing comment
2. BroadcastVote: more accurate for cal directPeers and directCount
3. markVote --> markVotes, improve efficiency
4. readBscCap-->readCap, in package bsc, bsc as default, so readCap is better
5. knownCache.Contains-->knownCache.contains
knownCache.Add-->knownCache.add
they are not used out of package
delete knownCache.Cardinality, useless
* ...

improve code of bsc p2p protocol

---

eth/handler_bsc_test.go
eth/protocols/bsc/peer.go

1. in func markVotes 
before adding hash to set, we should check if hash is already contained
otherwise, may lead to evict item, and add item already contained again
2. remove markVotes in AsyncSendVotes
because, sendVotes will be called following AsyncSendVotes
no need to double markVotes.
* ...

fix mini bug for markVotes

---

consensus/parlia/parlia.go
consensus/parlia/snapshot.go
core/forkchoice.go

1. snapshot of consensus may update invalid vote attestation before Lynn fork
2. new fork choice rule enabled after Boneh fork, which is expected after Lynn fork
1. before Lynn fork, we should only update valid vote attestation, check it before updating,
after Lynn fork, we don't need to check it any more, 
because header with invalid vote attestation (nill is legal here) will be rejected when imported, 
outputting warn log at the same time.
2. delay new fork choice rule after Lynn fork
* ...

fix vote attestation security flaw and enable new fork choice rule after Lynn fork

---

accounts/abi/bind/backends/simulated.go
core/blockchain_reader.go
eth/api.go
eth/api_backend.go
eth/filters/filter.go
eth/filters/filter_system_test.go
eth/gasprice/feehistory.go
eth/gasprice/feehistory_test.go
eth/gasprice/gasprice_test.go
ethclient/ethclient.go
ethclient/gethclient/gethclient.go
internal/ethapi/api.go
rpc/types.go

enhance GetBlockByNumber by supporting 'safe' and 'finalized', following Geth
1. follow up with Geth, to improve user experience, 'finalized' and 'safe' meaning, refer to
https://www.alchemy.com/overviews/ethereum-commitment-levels
2. transplant code from Geth, 
and the binding position is CurrentFinalBlock() and CurrentSafeBlock()
3. remove GetFinalizedHeader and GetJustifiedNumberAndHash in ethapi list
have been tested
curl -X POST "http://127.0.0.1:8545" -H "Content-Type: application/json"  --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", true],"id":1}'
curl -X POST "http://127.0.0.1:8545" -H "Content-Type: application/json"  --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["safe", true],"id":1}'
curl -X POST "http://127.0.0.1:8545" -H …

enhance GetBlockByNumber by supporting 'safe' and 'finalized', following Geth

---

core/state/database.go
core/state/statedb.go
trie/dummy_trie.go
trie/proof.go
trie/proof_test.go
trie/trie.go

- decouple code chunks in Prove() to traverseNodes()
- add ProveStorage()
- add VerifyProofStorage()
- modify GetStorageProof()
- add ExpireByPrefix() as a helper function to replace subtree with hash
- add getPrefixByKeys() as a helper function to get all prefix keys along a path
- add function comments
- add unit tests
* Trie interface implements a new function called ProveStorage()
* GetStorageProof takes in extra parameters for prefix key
* GetStorageProof uses ProveStorage() instead of Prove()

witness: generate and verify witness

---

common/math/integer.go
consensus/parlia/abi.go
consensus/parlia/parlia.go
consensus/parlia/parlia_test.go
consensus/parlia/snapshot.go

1. improve safety of CeilDiv
2. fix SignRecently in test
3. remove useless param of func prepareValidators
4. log whole header when Verify vote attestation fail
5. update abi about validatorSetABI
6. unify code style about validatorBytesLength
PS:
try to make least change to abi file,so 
1. copy abi.go file from develop branch
2. and change validatorSetABI to validatorSetABIBeforeBoneh 
3. add new validatorSetABI, use code in branch fast_finality_rebase
* ...

Fast finality abi and code style

---

core/state/database.go
core/state/statedb.go
core/state_transition.go
core/state_transition_test.go
core/types/revive_witness.go
core/types/revive_witness_test.go
core/types/transaction_test.go
core/vm/interface.go
light/trie.go
trie/dummy_trie.go
trie/proof.go
trie/proof_test.go
trie/secure_trie.go
trie/trie.go
trie/trie_test.go

- add StateDB.ReviveTrie() method
- add Trie.ReviveTrie() to revive trie given a Merkle proof
- add UTs
- add ReviveTrie on StateDB interface
- add ReviveTrie to Trie interface
- decouple revive codes in TransitionDb()
- change RootKey to RootKeyHex in MPTProofNub
- fix minor bugs
#76

Witness: MPT revive

---

core/state/database.go
core/state/journal.go
core/state/state_object.go
core/state/statedb.go
core/state_transition.go
core/vm/interface.go
trie/dummy_trie.go
trie/proof.go
trie/proof_test.go
trie/trie.go
trie/trie_test.go

add cache & journal support for state expiry, leave some TODOs about shadow nodes.
* state/journal: add revive journal;
* state/stateDB: opt revive state;
* state/state_object: record AccessedState, opt pending revive trie;
* state/journal: add access state journal;

EVM: add cache & journal support for state expiry

---

core/rawdb/accessors_shadow_node.go
core/rawdb/accessors_snapshot.go
core/rawdb/schema.go
core/state/statedb.go
go.mod
go.sum
trie/shadow_node.go
trie/shadow_node_difflayer.go
trie/shadow_node_history.go
trie/shadow_node_history_test.go
trie/shadow_node_test.go
trie/trie.go
trie/trie_test.go

support shadow node history store & query, and add more UTs.
* rawdb: handle shadow node history & changeSet & plainState; 
* trie/shadownode: support shadow node history store & query;
* trie/shadownode_difflayer: support diff layers flatten to DB;
* trie/shadownode: add more UTs;

feat(shadownode): support shadow node history store & query

---

trie/hasher.go
trie/node.go
trie/node_test.go
trie/proof_test.go
trie/secure_trie.go
trie/shadow_node.go
trie/trie.go
trie/trie_test.go

support shadow node hash calculation, opt some trie fields.
* trie/shadownode: support shadow node hash calculation

trie/shadownode: support shadow node hash calculation;

---

accounts/abi/bind/backends/simulated.go
accounts/external/backend.go
consensus/parlia/parlia.go
core/state/database.go
core/state/errors.go
core/state/state_object.go
core/state/statedb.go
core/tx_pool.go
core/types/receipt.go
core/types/transaction_signing.go
core/vm/evm.go
core/vm/gas_table.go
core/vm/operations_acl.go
internal/ethapi/api.go
trie/database.go
trie/errors.go
trie/hasher.go
trie/node.go
trie/shadow_node.go
trie/trie.go
trie/trie_test.go

fix: opt & fix some issues to support estimateWitness & revive expired state
* signer: fix txpool, codec bug with new ReviveTx & BEP215Signer;
* state/state_object: recall dirty revive trie for accuracy expired info;
* vm/evm: fix sstore calculate expired state gas bug;
* ethapi/api: fix EstimateGasAndReviveState resolve witness issues;
* trie/trie: opt shadow hash calculation, recalloect branch node epoch map;
* trie/trie: keep as hashNode when meet expired node, opt expired node checking;
* trie/trie: fix expired check bug when child is nil;
* state/database: fix reuse trie with shadow nodes bug;
* state/state_object: opt snap state query, opt insert dup check;
* state/statedb: fix copy bugs;
* trie/trie: opt trie root epoch bug, remove node's epoch methods;

fix: opt & fix some issues to support estimateWitness & revive expired state

---

trie/database.go

There's a case where if both parent and child nodes are expired, they will not be pruned.
Added a condition to prune the child node if the parent node is expired.

fix: add parent expired check for inline prune

---

trie/trie.go

trie/trie: opt trie update epoch, using copy to avoid node sharing;
* trie/trie: opt trie update epoch, using copy to avoid node sharing;
* ...

trie/trie: opt trie update epoch, using copy to avoid node sharing;

---

trie/committer.go
trie/database.go
trie/node.go
trie/secure_trie.go
trie/shadow_node.go
trie/shadow_node_test.go
trie/trie.go
trie/trie_test.go

Fix inline prune problem where storage trie couldn't be pruned properly.
* RootNode implements node interface
* RootNode is stored in TrieDb instead of ShadowNodeDb
* Expired nodes with epoch 0 will not be inline-pruned to avoid pruning account trie nodes. This is a temporary fix and can be refactored in the future
* cachedNode will store RootNode

fix(prune): storage trie now can be inline pruned

---

.github/workflows/commit-lint.yml
.github/workflows/integration-test.yml
.github/workflows/lint.yml
.github/workflows/unit-test.yml
consensus/parlia/parlia.go
core/state/state_object.go
core/state/trie_prefetcher.go
core/state_prefetcher.go
trie/proof.go
trie/trie.go

bugfix: fix state prefetcher concurrent bugs;
bugfix: fix trie epoch update bugs;

bugfix: fix state prefetcher concurrent bugs;

---

trie/proof.go
trie/triedb/pathdb/difflayer.go

trie/proof: fix pbss trie proof generate bug;

trie/proof: fix pbss trie proof generate bug;

---

core/state/state_object.go
core/types/revive_state.go
ethclient/gethclient/gethclient.go
ethclient/gethclient/gethclient_test.go
ethdb/fullstatedb.go
internal/ethapi/api.go
trie/proof.go
trie/trie.go

Modify `eth_getStorageReviveProof` to load storage trie using the latest block number if cannot load the contract trie directly from the RPC requests parameters.
If localDB is ahead of remoteDB, remoteDB may not be able to find the contract trie, causing missing trie node error.

rpc(revive): get from latest block num

---

core/state/database.go
core/state/state_expiry.go
core/state/state_object.go
internal/ethapi/api.go
light/trie.go
trie/dummy_trie.go
trie/errors.go
trie/proof.go
trie/proof_test.go
trie/secure_trie.go
trie/trie.go
trie/trie_expiry.go
trie/trie_test.go

feat: insert new slot in snapshot, prevent execution touch trie;
feat: reuse prefetcher tire? it could fetch from remoteDB;
feat: revive from local first, then fetch from remote;

feat: insert new slot in snapshot, prevent execution touch trie;

---

cmd/geth/config.go
core/state/state_expiry.go
core/state/state_object.go
core/state/trie_prefetcher.go
ethdb/fullstatedb.go
internal/ethapi/api.go
trie/trie_test.go

- Subfetcher now revive states in batches instead of individually
- Add trie revive unit tests
- RemoteDB will cache storage proof requests
- User can only enable state expiry with PBSS

core/state, trie, api: batch mode revive, remoteDB cache, unit tests

---

cmd/geth/config.go
cmd/geth/main.go
cmd/geth/snapshot.go
cmd/utils/flags.go
core/blockchain.go
core/blockchain_insert.go
core/blockchain_reader.go
core/rawdb/accessors_epoch_meta.go
core/rawdb/database.go
core/rawdb/schema.go
core/state/iterator.go
core/state/pruner/pruner.go
core/state/snapshot/snapshot_expire.go
core/state/snapshot/snapshot_expire_test.go
core/state/state_expiry.go
core/state/state_object.go
core/state/statedb.go
core/state/trie_prefetcher.go
core/types/state_epoch.go
core/types/state_expiry.go
eth/backend.go
eth/ethconfig/config.go
eth/state_accessor.go
params/config.go
trie/inspect_trie.go
trie/trie.go

pruner: opt size statistic;
trie/inspect: opt inspect in PBSS mode;
flags: refactor state expiry config;

State expiry mvp0.1: opt prune stats & state expiry config;

---

core/state/state_expiry.go
core/state/sync.go
eth/backend.go
eth/downloader/downloader.go
eth/downloader/statesync.go
eth/handler.go
eth/protocols/snap/handler.go
eth/protocols/snap/sync.go
eth/protocols/snap/sync_test.go
trie/proof.go
trie/stacktrie.go
trie/sync.go
trie/trie.go
trie/trie_reader.go

- Support state expiry for snap sync
- May not be suitable for consensus version. In consensus version, nodes need to request epoch meta from peers.

feat(snap): add state expiry support to snap sync

---

cmd/geth/chaincmd.go
cmd/geth/config.go
cmd/geth/consolecmd.go
cmd/geth/dbcmd.go
cmd/geth/snapshot.go
cmd/geth/verkle.go
core/blockchain.go
core/state/pruner/pruner.go
core/state/snapshot/snapshot_value.go
core/state/state_expiry.go
core/state/state_object.go
core/state/statedb.go
core/types/state_expiry.go
trie/database.go
trie/epochmeta/database.go
trie/epochmeta/database_test.go
trie/epochmeta/difflayer.go
trie/epochmeta/difflayer_test.go
trie/epochmeta/disklayer.go
trie/epochmeta/snapshot.go
trie/epochmeta/snapshot_test.go
trie/trie.go
trie/trie_expiry.go
trie/trie_reader.go
trie/triedb/pathdb/layertree.go

pruner: fix some prune bugs;
trie/epochmeta: add bloom filter, opt lock;
metrics: add some trace metrics for epoch meta;
trie/trie: fix some update epoch bugs;
state/state_object: fix epoch update issue;
state/statedb: fix oom issue;

State expiry mvp0.1: testnet bugs fixed;

---

core/state/snapshot/generate.go
core/state/snapshot/generate_test.go
ethclient/gethclient/gethclient.go
ethclient/gethclient/gethclient_test.go
trie/trie_test.go

Checks the values read from the database are with epoch or without epoch. Perform trie proof verification with only the pure values (i.e. without epoch).

core/state: fix snapshot recovery

---

core/state/pruner/pruner.go
core/state/snapshot/snapshot_expire.go
core/state/state_expiry.go
trie/committer.go
trie/epochmeta/database.go
trie/epochmeta/disklayer.go
trie/inspect_trie.go
trie/proof.go
trie/tracer.go
trie/trie.go
trie/trie_expiry.go
trie/trie_reader.go
trie/triedb/pathdb/difflayer.go
trie/triedb/pathdb/disklayer.go
trie/triedb/pathdb/nodebuffer.go
trie/trienode/node.go

trie: opt trie update;
trie: fix rebase error;
pruner: opt expired prune, add more logs;

State expiry mvp0.1: opt performance & opt prune;
