node-real/bsc

- eth/handler.go
> Add the check of whether nil votePool in handler

- core/vote/vote_pool.go
- core/vote/vote_pool_test.go
> Update Unit Test of Vote Pool

- consensus/parlia/abi.go
> Update contracts' ABI

- cmd/geth/main.go
- cmd/geth/usage.go
- cmd/utils/flags.go
- consensus/consensus.go
- consensus/parlia/parlia.go
- core/vote/vote_manager.go
- core/vote/vote_pool.go
- core/vote/vote_pool_test.go
- core/vote/vote_signer.go
- eth/backend.go
- node/config.go
> Resolved comments

- consensus/parlia/parlia.go
- eth/catalyst/api_test.go
- eth/handler_eth_test.go
- params/config.go
> Update for LynnFork

- cmd/geth/blsaccountcmd.go
- consensus/parlia/parlia.go
- consensus/parlia/snapshot.go
> fix comments

- core/blockchain.go
- core/headerchain.go
- ethclient/ethclient.go
- internal/ethapi/api.go
> export get highest justified or finalized block

- core/systemcontracts/upgrade.go
> Fix error of applySystemContractUpgrade

- consensus/parlia/parlia.go
- core/vm/contracts.go
- params/config.go
> First round final review comments fixed

- consensus/consensus.go
- consensus/parlia/parlia.go
- core/vote/vote_journal.go
- core/vote/vote_manager.go
- core/vote/vote_pool.go
- core/vote/vote_pool_test.go
- eth/backend.go
> Resolve final review comments

- core/vote/vote_pool_test.go
> minor update

- cmd/geth/blsaccountcmd.go
- consensus/consensus.go
- consensus/parlia/parlia.go
- consensus/parlia/parlia_test.go
- consensus/parlia/snapshot.go
- core/blockchain.go
- core/headerchain.go
- core/types/vote.go
- core/vote/vote_manager.go
- core/vote/vote_pool.go
- core/vote/vote_pool_test.go
- eth/fetcher/block_fetcher.go
- ethclient/ethclient.go
- internal/ethapi/api.go
> fix consensus related comments

- accounts/abi/bind/backends/simulated.go
- consensus/consensus.go
- consensus/parlia/parlia.go
- core/blockchain.go
- core/events.go
- core/headerchain.go
- eth/api_backend.go
- eth/filters/api.go
- eth/filters/filter.go
- eth/filters/filter_system.go
- eth/filters/filter_system_test.go
- ethclient/ethclient.go
- internal/ethapi/api.go
- internal/ethapi/backend.go
- les/api_backend.go
- light/lightchain.go
- mobile/ethclient.go
> Add subscribe finalized header API

- core/blockchain.go
> Fix wrong type event issue

- consensus/parlia/parlia.go
- consensus/parlia/ramanujanfork.go
> fix the backoff time after boneh fork

- cmd/geth/blsaccountcmd.go
- core/vm/contracts.go
- core/vm/contracts_test.go
- core/vote/vote_pool.go
- eth/filters/filter_system.go
- eth/protocols/eth/handlers.go
- eth/protocols/eth/protocol_test.go
- params/config.go
> Fix some audit comments

- consensus/parlia/parlia.go
- core/blockchain.go
- core/headerchain.go
- eth/backend.go
- params/config.go
1. Fix the fork order check
2. Fix get vote attestation
3. Fix reorg logic of fast finality
The pervious logic is wrong, we should fix them.
NA
* NA
> core: fix several bugs

- accounts/abi/bind/backends/simulated.go
- core/state_transition.go
- core/types/access_list_tx.go
- core/types/dynamic_fee_tx.go
- core/types/legacy_tx.go
- core/types/revive_state_tx.go
- core/types/revive_witness.go
- core/types/transaction.go
- core/types/transaction_marshalling.go
- core/types/transaction_signing.go
- core/types/transaction_test.go
- interfaces.go
- internal/ethapi/transaction_args.go
- les/odr_test.go
- light/odr_test.go
- params/config.go
- tests/state_test_util.go
- add revive state transaction; 
- message support `witnessList`; 
- fix some ut;
- add revive state tx uts;
* core/transaction: add revive state transaction; 
* message support `witnessList`;
> core/transaction: add revive state transaction;

- consensus/parlia/parlia.go
improve log style when Verify vote attestation fail
* ...
> improve log style when Verify vote attestation fail

- consensus/parlia/parlia.go
distribute additional reward for collecting redundant votes
Validators who assemble vote attestation can get additional reward. The value of reward is proportional to the number of redundant votes
* ...
> distribute additional reward for collecting redundant votes

- cmd/evm/internal/t8ntool/transaction.go
- core/bench_test.go
- core/state_transition.go
- core/state_transition_test.go
- core/tx_pool.go
- core/types/revive_state_tx.go
- core/types/revive_witness.go
- core/types/transaction_test.go
- light/trie.go
- light/txpool.go
- params/protocol_params.go
- tests/transaction_test_util.go
core/transaction: add revive state gas computation;
* opt witness definition;
* add `witnessList` gas for `IntrinsicGas`;
* add some UTs;
> core/transaction: add revive state gas computation;

- core/state_transition.go
- core/state_transition_test.go
- core/tx_pool.go
- core/types/revive_state_tx.go
- core/types/revive_witness.go
- core/types/revive_witness_test.go
- core/types/transaction_test.go
- light/txpool.go
- params/config.go
- params/protocol_params.go
- trie/database.go
- trie/node.go
- trie/proof.go
- trie/proof_test.go
add witness format verify, more friendly for revive state.
* txpool: add hard fork & witness check;
* trie: add MPTProofCache, include verify proof, MPTProofNubs;
* trie: add trie node type;
* core/StateTransition: add witness verify;
> core/ReviveWitness: refactor witness definition, add verify witness;

- trie/database.go
- trie/errors.go
- trie/node.go
- trie/shadownodes.go
- trie/trie.go
> implement MPT and shadow node

- core/state/database.go
- light/trie.go
- trie/dummy_trie.go
- trie/secure_trie.go
- trie/trie.go
- trie/trie_test.go
add cache mechanism to MPT Revive feature
* ReviveTrie no longer has a return value
* Revive feature is split into ReviveTrie, TryRevive, and tryRevive functions
* Change to Trie interface
> refactor(trie): update ReviveTrie to include cache mechanism

- .github/workflows/build-test.yml
- .github/workflows/commit-lint.yml
- .github/workflows/integration-test.yml
- .github/workflows/lint.yml
- .github/workflows/unit-test.yml
- core/state/state_object.go
- core/state_transition_test.go
- core/types/revive_state_tx.go
- core/types/revive_witness.go
- core/types/revive_witness_test.go
- core/types/state_epoch.go
- core/types/state_epoch_test.go
- core/types/transaction_test.go
- trie/dummy_trie.go
- trie/errors.go
- trie/proof.go
- trie/proof_test.go
- trie/shadow_node.go
- trie/trie.go
- trie/trie_test.go
add shadow node storage interface for trie querying shadow nodes;
* trie/shadow_node: add shadow node storage;
* fix: fix some compile error and ut failures;
> trie/shadow_node: add shadow node storage interface

- core/state/database.go
- core/state/state_object.go
- light/trie.go
- trie/dummy_trie.go
- trie/proof.go
- trie/secure_trie.go
- trie/trie.go
- trie/trie_test.go
modify the return value of ReviveTrie to include successfully revived nubs
> refactor(trie): track successful nubs for ReviveTrie

- cmd/geth/snapshot.go
- core/blockchain.go
- core/state/database.go
- core/state/pruner/pruner.go
- core/state/snapshot/generate_test.go
- eth/api.go
- eth/protocols/snap/handler.go
- eth/protocols/snap/sync_test.go
- les/downloader/downloader_test.go
- trie/database.go
- trie/iterator_test.go
- trie/node.go
- trie/secure_trie.go
- trie/secure_trie_test.go
- trie/shadow_node.go
- trie/shadownodes.go
- trie/sync_test.go
- trie/trie.go
draft an implement of read and write of MPT and shadow nodes.
Since node may be expired, the MPT Read and write should have related changes.
None
* ...
> State expire: implementation of MPT R&W

- accounts/abi/bind/backends/simulated.go
- accounts/abi/bind/backends/simulated_test.go
- core/state/statedb.go
- core/vm/errors.go
- core/vm/evm.go
add gas estimation and revive state simulation feature
* added EstimateGasReviveState function
* added UT
* modified EVMError struct
* modified EVM struct
UTs are not completed because currently there's no way of simulating the expired state. Will revisit this again.
> feat(simulation): add EstimateGasReviveState

- ethclient/ethclient.go
- ethclient/ethclient_test.go
- internal/ethapi/api.go
add "eth_estimateGasAndReviveState" new RPC method
* add new function EstimateGasAndReviveState() to client and API
> feat(RPC): add EstimateGasAndReviveState RPC method

- trie/proof.go
- trie/proof_test.go
- trie/trie.go
- trie/trie_test.go
add shadow logic to trie revive
* modify ReviveTrie()
* fix MPT insert error
> refactor(trie): modify ReviveTrie to include shadow logic

- core/state/database.go
- trie/hasher.go
- trie/node.go
- trie/node_test.go
- trie/secure_trie.go
- trie/shadow_node.go
- trie/shadow_node_test.go
- trie/trie.go
- trie/trie_test.go
fix some trie epoch update bugs, store shadow node in a simple version, will revert in later cryyl's version.
* trie: fix some epoch update bugs; 
* trie/shadownode: support commit root node & shadow nodes;
> trie: fix some epoch update bugs;

- accounts/abi/bind/backends/simulated.go
- internal/ethapi/api.go
do not create a witness if proof is nil
> fix: add proof nil check

- cmd/evm/internal/t8ntool/execution.go
- core/blockchain.go
- core/chain_makers.go
- core/rawdb/schema.go
- core/state/pruner/pruner.go
- eth/backend.go
- light/trie.go
- trie/shadow_node_difflayer.go
- trie/shadow_node_difflayer_test.go
- trie/shadow_node_history_test.go
- trie/shadow_node_test.go
- trie/trie_test.go
support expired snap kv & shadow node history prune;
* state/pruner: support expired snap kv prune;
* trie/shadow_node_history: remove history when in pruning mode;
> feat(prune): support expired snap kv & shadow node history prune;

- core/blockchain.go
- core/rawdb/database.go
- core/state/errors.go
- core/state/pruner/pruner.go
- core/state/state_object.go
- core/state/statedb.go
- miner/worker.go
fix: fix some issues when storage testing;
* pruner: opt init with chain config;
* state/statedb: generate witness fron pendingReviveTrie;
* log: add some logs;
> fix: fix some issues when storage testing;

- cmd/geth/snapshot.go
- core/blockchain.go
- core/state/pruner/pruner.go
- core/state/snapshot/snapshot_expire.go
- core/state/snapshot/snapshot_expire_test.go
pruner: support PBSS expired state prune;
> pruner: support PBSS expired state prune;
